{% set name = "pickle5" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6b181805c6d7bde1d2932429385d7ff5eb1eb6bb8e596d5bd646c39768686a2

build:
  number: 0
  skip: true  # [py<36 or py>37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pickle5
  commands:
    - python -m pickle5.test.test_pickle

about:
  home: https://github.com/pitrou/pickle5-backport
  license: PSF 2
  license_file: LICENSE
  summary: "Experimental backport of the pickle 5 protocol (PEP 574)"

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
