appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: oQiNztuPJkCtkrjmdVcZpwz75K0dK9nrZ+YQ6p9ewL+PjHXNWvYAU05P4mo68pyvrUAk9YBDlcK9SGMVGtDiJ5T/lRVCyVZXtVOiqg0437lcS0nXObNFg3qLLwGqQay3TCwYMLTIdMXhG+csmC18OfZZTp0RkgWvqyMEnAObKYadhYxIW60amkO9IIAfSmRSSRtcVBt1TMrvRekfvgapJ7P4oWxxzqTsZDZNQ4S7/KY5xkRLlXTTPAlguHYO6E/tPf2NfvfXvIrcPbe5rKOkdwNI0T0ToAf1uX4PsTRLNNrM4x08vhIl9KiiQgjQg1QrvPrbIzyyp54H2vSC7w+tc0/EP+CGpFgqe+3V3r94DM8vAvbvu/RLqFbQjTmKDAcDPfzog6O3vvv/DV4adsIm3Ul2AvyZsxnsnm15yQz6vOYSm0NOWgiv3SGCPKiC/BkTb/DJbpkjpD01dpOBXnG8YNuJ/rOZfkciYxEEqUdXYzcSE+xm6Cba3OQRa4NyoTeW9mfI+/AfhA9MDoU3X1SzmOxT+uB9zsVZRR0aiSGCLDayCUCBqso2IuRxrIIamwATKFttgvvFeRUTSJVzRXM+7KNnPcAsh557vujEYW+e4N06xYGpRl2+LsYQPlLv+4zBhZ5Plf0xULMiZwmSDtYbrfo1T8USrWkx1Ejdzxl+bOA=}
provider:
  win: azure
conda_forge_output_validation: true
